---
title: <p style="text-align:center;">GGPLOT2</p>
author: <p style="text-align:center;">Wenjun ZHAO</p>
date: <p style="text-align:center;">12/9/2020</p>
output:
  html_document: default
  pdf_document: default
---

<span style="font-size:24px;"> **Overview**</span>

ggplot2 est un système de création graphique déclarative, basé sur The Grammar of Graphics. Vous fournissez les données, dites à ggplot2 comment mapper des variables à l'esthétique, quelles primitives graphiques utiliser et il s'occupe des détails.

<span style="font-size:24px;"> **Installation**</span>

Le moyen le plus simple d'obtenir ggplot2 est d'installer tout le tidyverse:

<span style="background-color:yellow;">*install.packages("tidyverse")*</span>

Sinon, installez simplement ggplot2:

<span style="background-color:yellow;">*install.packages("ggplot2")*</span>

Ou la version de développement de GitHub:

<span style="background-color:yellow;">*install.packages ("devtools")*</span>

<span style="background-color:yellow;">*devtools::install_github("tidyverse/ggplot2")*</span>

<span style="font-size:24px;"> **Utilisation**</span>

Il est difficile de décrire succinctement le fonctionnement de ggplot2 car il incarne une philosophie profonde de la visualisation. Cependant, dans la plupart des cas, vous commencez avec *ggplot ()*, fournissez un jeu de données et une cartographie esthétique (*avec aes ()*). Vous ajoutez ensuite des couches (*comme geom_point ()* ou *geom_histogram ()*), des échelles (*comme scale_colour_brewer ()*), des spécifications de facettes (*comme facet_wrap ()*) et des systèmes de coordonnées (*comme coord_flip ()*).


```{r}
library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

