---
title: "Analyse de ggplot2 par WENJUN ZHAO"
author: "Wenjun ZHAO"
date: "12/20/2020"
output: pdf_document
bibliography : ggplot2.bib
---

# I. Introduction

Vous pouvez retrouver mon travail sur mon Github, **https://github.com/claudia0524/PSBX**.

Pour ce dossier, nous avons étudier mon travail de ggplot2, étudiant en M2DM au sein de PSB.

Nous avons trouvé son dossier sur son Github : **https://github.com/claudia0524/PSBX**

Maintenant, nous allons établir mes 5 critères d'évaluations, qui seront les mêmes pour tout les dossiers que j'ai vais étudier pour ce devoir:

**Les cinq critères d'évaluation**

*1. Rmd se comporte bien à l'exécution*

*2. Les aspects intéressant, didactique, complet*

*3. La qualité Rmarkdown, la qualité de l'écriture*

*4. Didactique, conformité aux exigences vues plus haut et comporte du calcul symbolique et du calcul numérique*

*5. La qualité du LaTeX et des illustrations, la qualité de l'écriture, le choix des ressource internet, la compréhension personnelle des concepts*

# II. Synthèse du travail en question

ggplot2 est un système de création graphique déclarative, basé sur The Grammar of Graphics. Vous fournissez les données, dites à ggplot2 comment mapper des variables à l'esthétique, quelles primitives graphiques utiliser et il s'occupe des détails.

Nous allons maintenant étudier mon code dans le chapitre suivant.

# III. Extrait commenté des parties de code

# Installation

Le moyen le plus simple d'obtenir ggplot2 est d'installer tout le tidyverse:[@Wenjun]

*install.packages("tidyverse")*

Sinon, installez simplement ggplot2:

*install.packages("ggplot2")*

Ou la version de développement de GitHub:

*install.packages ("devtools")*

*devtools::install_github("tidyverse/ggplot2")*

# Utilisation

Il est difficile de décrire succinctement le fonctionnement de ggplot2 car il incarne une philosophie profonde de la visualisation. Cependant, dans la plupart des cas, vous commencez avec *ggplot ()*, fournissez un jeu de données et une cartographie esthétique (*avec aes ()*). Vous ajoutez ensuite des couches (*comme geom_point ()* ou *geom_histogram ()*), des échelles (*comme scale_colour_brewer ()*), des spécifications de facettes (*comme facet_wrap ()*) et des systèmes de coordonnées (*comme coord_flip ()*)[@online].


```{r}
library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

# IV. Evaluation du travail en question

*1. Rmd se comporte bien à l'exécution (4/4)*

*2. Les aspects intéressant, didactique, complet (3/4)*

*3. La qualité Rmarkdown, la qualité de l'écriture (2/4)*

*4. Didactique, conformité aux exigences vues plus haut et comporte du calcul symbolique et du calcul numérique (2/4)*

*5. La qualité du LaTeX et des illustrations, la qualité de l'écriture, le choix des ressource internet, la compréhension personnelle des concepts (2/4)*

# V. Conclusion

En général, ce travail exécuse bien dans l'environement de R. Et il nous explique clairement comment fonctionner le package Dplyr dans un rmd, On comprend rapidement le but principal de ce package. L'aspect est intéressant, complet et propre. D'ailleurs, il a expliqué chaque code, on peut les comprendre facilement. Il a présenté des fonctions qui peut être utile pour analyser des données dans les rapports. La qualité Rmarkdown, la qualité de l'écriture et La qualité du LaTeX sont ainsi bien.

# VI. Bibliographie