---
title: "GGPLOT2"
author: "Wenjun ZHAO"
date: "12/9/2020"
output:
  pdf_document: default
  html_document: default
---

# Overview

ggplot2 est un système de création graphique déclarative, basé sur The Grammar of Graphics. Vous fournissez les données, dites à ggplot2 comment mapper des variables à l'esthétique, quelles primitives graphiques utiliser et il s'occupe des détails.

# Installation

Le moyen le plus simple d'obtenir ggplot2 est d'installer tout le tidyverse:

*install.packages("tidyverse")*

Sinon, installez simplement ggplot2:

*install.packages("ggplot2")*

Ou la version de développement de GitHub:

*install.packages ("devtools")*

*devtools::install_github("tidyverse/ggplot2")*

# Utilisation

Il est difficile de décrire succinctement le fonctionnement de ggplot2 car il incarne une philosophie profonde de la visualisation. Cependant, dans la plupart des cas, vous commencez avec *ggplot ()*, fournissez un jeu de données et une cartographie esthétique (*avec aes ()*). Vous ajoutez ensuite des couches (*comme geom_point ()* ou *geom_histogram ()*), des échelles (*comme scale_colour_brewer ()*), des spécifications de facettes (*comme facet_wrap ()*) et des systèmes de coordonnées (*comme coord_flip ()*).


```{r}
library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

